import type { Review, Stay } from "@/types";

export const SEED_STAYS: Stay[] = [
  {
    id: "stay-lisboa-river",
    title: "Riverlight Apartment — Alfama",
    city: "Lisboa",
    country: "Portugal",
    description:
      "Sun-filled two-bedroom near the river, walking distance to miradouros and trams. Ideal for slow mornings and long dinners.",
    imageUrl:
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80",
    propertyType: "apartment",
    basePricePerNight: 118,
    currency: "EUR",
    cleaningFee: 45,
    maxGuests: 4,
    ratingAvg: 4.8,
    reviewCount: 3,
    amenities: ["Wi‑Fi", "Kitchen", "Washer", "Air conditioning"],
    blockedRanges: [{ start: "2026-06-10", end: "2026-06-14" }],
  },
  {
    id: "stay-porto-loft",
    title: "Design Loft near Clérigos",
    city: "Porto",
    country: "Portugal",
    description:
      "High ceilings, local art, and a quiet street minutes from downtown. Perfect base for food tours and Douro day trips.",
    imageUrl:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80",
    propertyType: "apartment",
    basePricePerNight: 96,
    currency: "EUR",
    cleaningFee: 35,
    maxGuests: 3,
    ratingAvg: 4.6,
    reviewCount: 2,
    amenities: ["Wi‑Fi", "Workspace", "Elevator"],
    blockedRanges: [{ start: "2026-07-01", end: "2026-07-05" }],
  },
  {
    id: "stay-evora-boutique",
    title: "Boutique Hotel Évora Old Town",
    city: "Évora",
    country: "Portugal",
    description:
      "Small hotel with courtyard pool, breakfast included, and staff who know every cork forest tour worth taking.",
    imageUrl:
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&q=80",
    propertyType: "hotel",
    basePricePerNight: 132,
    currency: "EUR",
    cleaningFee: 0,
    maxGuests: 2,
    ratingAvg: 4.9,
    reviewCount: 2,
    amenities: ["Breakfast", "Pool", "Parking", "24h desk"],
    blockedRanges: [],
  },
  {
    id: "stay-lagos-hostel",
    title: "Lagos Surf Hostel — Shared & private rooms",
    city: "Lagos",
    country: "Portugal",
    description:
      "Steps from the cliffs, boards for rent, and a rooftop for golden hour. Mix of dorms and private doubles.",
    imageUrl:
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80",
    propertyType: "hostel",
    basePricePerNight: 38,
    currency: "EUR",
    cleaningFee: 12,
    maxGuests: 6,
    ratingAvg: 4.4,
    reviewCount: 2,
    amenities: ["Shared kitchen", "Surf rental", "Lockers"],
    blockedRanges: [{ start: "2026-08-01", end: "2026-08-10" }],
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: "rev-1",
    stayId: "stay-lisboa-river",
    author: "Marta",
    rating: 5,
    text: "Beautiful light, great coffee shops nearby, host was responsive.",
    createdAt: "2026-01-12T10:00:00.000Z",
    status: "visible",
  },
  {
    id: "rev-2",
    stayId: "stay-lisboa-river",
    author: "Jon",
    rating: 5,
    text: "Walkable to everything. Would stay again.",
    createdAt: "2026-02-03T14:22:00.000Z",
    status: "visible",
  },
  {
    id: "rev-3",
    stayId: "stay-lisboa-river",
    author: "Sam",
    rating: 4,
    text: "Stairs are steep — pack light. Otherwise perfect.",
    createdAt: "2026-03-01T09:15:00.000Z",
    status: "visible",
  },
  {
    id: "rev-4",
    stayId: "stay-porto-loft",
    author: "Inês",
    rating: 5,
    text: "Spotless and quiet. Loved the neighborhood bakeries.",
    createdAt: "2026-01-20T16:40:00.000Z",
    status: "visible",
  },
  {
    id: "rev-5",
    stayId: "stay-porto-loft",
    author: "Alex",
    rating: 4,
    text: "Great space; a bit warm in August without AC in the bedroom.",
    createdAt: "2026-02-11T11:05:00.000Z",
    status: "visible",
  },
  {
    id: "rev-6",
    stayId: "stay-evora-boutique",
    author: "Rui",
    rating: 5,
    text: "Pool and breakfast made the trip. Staff recommendations were gold.",
    createdAt: "2026-02-28T08:50:00.000Z",
    status: "visible",
  },
  {
    id: "rev-7",
    stayId: "stay-evora-boutique",
    author: "Claire",
    rating: 5,
    text: "Charming hotel, easy walk to Roman temple ruins.",
    createdAt: "2026-03-10T19:12:00.000Z",
    status: "visible",
  },
  {
    id: "rev-8",
    stayId: "stay-lagos-hostel",
    author: "Diego",
    rating: 4,
    text: "Social vibe, clean dorms, short walk to beaches.",
    createdAt: "2026-01-05T12:00:00.000Z",
    status: "visible",
  },
  {
    id: "rev-9",
    stayId: "stay-lagos-hostel",
    author: "Emma",
    rating: 5,
    text: "Rooftop sunsets every night. Met great people.",
    createdAt: "2026-02-02T09:30:00.000Z",
    status: "visible",
  },
];
